### ISSUE TITLE
SSL Issue?

### ISSUE THREAD

**Issue by pydevlance** [Vadims06/topolograph-docker#11]
┌─[✗]─[parrot@parrot]─[~/Documents/Topograph/topolograph-docker]
└──╼ $docker --version
Docker version 20.10.22, build 3a2c30b

┌─[parrot@parrot]─[~/Documents/Topograph/topolograph-docker]
└──╼ $python3 --version
Python 3.9.2

Traceback:
─[parrot@parrot]─[~/Documents/Topograph/topolograph-docker]
└──╼ $docker-compose up -d
Traceback (most recent call last):
  File "/home/parrot/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/parrot/.local/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/home/parrot/.local/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/home/parrot/.local/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/home/parrot/.local/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/home/parrot/.local/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/home/parrot/.local/lib/python3.9/site-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

**Comment by pydevlance** [comment]
forgot,
─[✗]─[parrot@parrot]─[~/Documents/Topograph/topolograph-docker]
└──╼ $docker-compose --version
docker-compose version 1.29.2, build unknown

**Comment by pydevlance** [comment]
I installed again a self signed but still errors.

**Comment by pydevlance** [comment]
I've corrected the issues, however it doesnt run as I am not seeing any containers load thus getting a 502 bad gateway at localhost:8080

sudo docker-compose pull
[sudo] password for parrot: 
Pulling mongodb   ... done
Pulling flask     ... done
Pulling webserver ... done

sudo docker-compose up -d
Creating network "topolograph_backend" with driver "bridge"
Creating network "topolograph-docker_frontend" with driver "bridge"
Creating volume "topolograph-docker_mongodbdata" with local driver
Creating volume "topolograph-docker_nginxdata" with local driver
Creating mongodb ... done
Creating flask   ... done
Creating webserver ... done

docker ps
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

**Comment by Vadims06** [comment]
Hi @pydevlance ,
If you start docker-compose under sudo, please use sudo with `sudo docker ps`

**Comment by pydevlance** [comment]
I see the stuff now, wasnt aware sudo was then required.. 
I have the webpage up now, but I also cloned the topology repo into the topology-docker dir.. not sure it that was requried todo so.

**Comment by Vadims06** [comment]
I'm not sure if it still applicable. I recorded video with quick setup of Topolograph suite https://youtu.be/imtVbqQYVWQ. Please check it out and try to use `install.sh` script to recreate the environment
