### ISSUE TITLE
flask is continuing to restart 

### ISSUE THREAD

**Issue by jgomez177** [Vadims06/topolograph-docker#4]
2023-02-01 13:49:47 Traceback (most recent call last):
2023-02-01 13:49:47   File "/usr/local/bin/gunicorn", line 8, in <module>
2023-02-01 13:49:47     sys.exit(run())
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
2023-02-01 13:49:47     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 228, in run
2023-02-01 13:49:47     super().run()
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2023-02-01 13:49:47     Arbiter(self).run()
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
2023-02-01 13:49:47     self.halt(reason=inst.reason, exit_status=inst.exit_status)
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
2023-02-01 13:49:47     self.stop()
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
2023-02-01 13:49:47     time.sleep(0.1)
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2023-02-01 13:49:47     self.reap_workers()
2023-02-01 13:49:47   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2023-02-01 13:49:47     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2023-02-01 13:49:47 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-02-01 13:49:47 Helpers
2023-02-01 13:49:47 ['system.users', 'system.version']

**Comment by Vadims06** [comment]
Hi @jgomez177 , acknowledge, v2.29 constantly rebooting, v2.28 works fine. I will have a look at it. Thank you.

**Comment by Vadims06** [comment]
it happens because of https://github.com/p1c2u/openapi-spec-validator/issues/173

**Comment by BrianDavisson** [comment]
@Vadims06  Thanks for the fix how do I down level to v2.28? @jgomez177 kudo's to you for reporting the issue.

**Comment by Vadims06** [comment]
Hi @BrianDavisson, you can set exact version in `docker-compose.yml` file in this line `image: vadims06/topolograph:2.28` or leave it as is `image: vadims06/topolograph:latest`. I think I fix the issue in `2.29`, `2.29.1` and `latest`. Please check and give me an update.

**Comment by aliraqbachelor** [comment]
If it's not too much trouble, could you assist me with the vadims06/topolograph? I have downloaded it, but whenever I try to create a container,

PS C:\ docker run --name topolograph -p 8080:80 -d vadims06/topolograph
e065a8b837e37880aebc594dbd4effa02d639cc6565fc5fffe611a7eff81a710

 I receive the following message in my terminal: 
log.
2023-02-19 19:22:03 [2023-02-19 16:22:03 +0000] [1] [INFO] Starting gunicorn 20.0.4
2023-02-19 19:22:03 [2023-02-19 16:22:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2023-02-19 19:22:03 [2023-02-19 16:22:03 +0000] [1] [INFO] Using worker: sync
2023-02-19 19:22:03 [2023-02-19 16:22:03 +0000] [7] [INFO] Booting worker with pid: 7
2023-02-19 19:22:03 [2023-02-19 16:22:03 +0000] [8] [INFO] Booting worker with pid: 8
2023-02-19 19:22:04 [2023-02-19 16:22:04 +0000] [9] [INFO] Booting worker with pid: 9
2023-02-19 19:22:04 [2023-02-19 16:22:04 +0000] [10] [INFO] Booting worker with pid: 10
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [7] [INFO] Worker exiting (pid: 7)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [8] [INFO] Worker exiting (pid: 8)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [9] [INFO] Worker exiting (pid: 9)
2023-02-19 19:22:34 [2023-02-19 16:22:34 +0000] [10] [INFO] Worker exiting (pid: 10)
2023-02-19 19:22:34 config

**Comment by Vadims06** [comment]
Hi @aliraqbachelor , sure I can help, but before this could you please clarify the intention to run Topolograph container only, because it doesn't work without mongoDB and nginx server. That's why they are combined on docker-compose file. To launch it - run docker-compose up -d.

**Comment by aliraqbachelor** [comment]
oh im new in docker community , but it seems that there is an issue with the installation of Docker Compose on my Windows system.
I am greatly appreciative of your hard work on this tool, as it has been extremely helpful for me. It might be worth considering including this tool with BGP and SRv6 in the next update. all the best

**Comment by Vadims06** [comment]
Thank you for your feedback, could you please describe more use cases of implementing BGP into Topolograph? Do you want to see the topology or track bgp changes?..

**Comment by aliraqbachelor** [comment]
Sure, in my case we use ISIS/IPv6 as an underlying protocol in combination with both  , the Vander is huawei , where topo. Return empty for ipv6 lsdp

**Comment by Vadims06** [comment]
Great case, would you like to add Isis/ipv6 support for Topolograph? What do I need is the output of Isis lsdb...

**Comment by aliraqbachelor** [comment]
That Will be good, i have email u @admin topo , Thank you

**Comment by BrianDavisson** [comment]
Thanks for getting the fix out. I'll get it setup and take a look at it!

**Comment by Vadims06** [comment]
Hi @change48 , thank you for your feedback. I've just re-uploaded v2.34/latest version, please check.

**Comment by change48** [comment]
/

> Hi @change48 , thank you for your feedback. I've just re-uploaded v2.34/latest version, please check.

Hi @Vadims06 ，test latest 2.34 works fine, thanks for your quick response.
