### ISSUE TITLE
Failing to launch (Docker Desktop for Windows)

### ISSUE THREAD

**Issue by nzjc** [Vadims06/topolograph-docker#8]
I'm using the latest (4.32) Docker Desktop for Windows 10, using WSL2 as the VM backend. 

Try to run the container (pulled from this repo this morning -2.39) and it fails to launch, log below.

Hopefully it's just me doing something silly.

```
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [1] [INFO] Using worker: sync
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [7] [INFO] Booting worker with pid: 7
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [8] [INFO] Booting worker with pid: 8
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [9] [INFO] Booting worker with pid: 9
2024-07-12 10:54:08 [2024-07-11 22:54:08 +0000] [10] [INFO] Booting worker with pid: 10
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [7] [ERROR] Exception in worker process
2024-07-12 10:54:38 Traceback (most recent call last):
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2024-07-12 10:54:38     worker.init_process()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
2024-07-12 10:54:38     self.load_wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2024-07-12 10:54:38     self.wsgi = self.app.wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-07-12 10:54:38     self.callable = self.load()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2024-07-12 10:54:38     return self.load_wsgiapp()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2024-07-12 10:54:38     return util.import_app(self.app_uri)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
2024-07-12 10:54:38     mod = importlib.import_module(module)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-07-12 10:54:38     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap_external>", line 1181, in exec_module
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-07-12 10:54:38   File "routes.pyx", line 8, in init routes
2024-07-12 10:54:38   File "Helpers.pyx", line 3859, in init Helpers
2024-07-12 10:54:38   File "Helpers.pyx", line 3234, in Helpers.DBHelper.__init__
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/database.py", line 1468, in authenticate
2024-07-12 10:54:38     self.client._cache_credentials(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 749, in _cache_credentials
2024-07-12 10:54:38     server = self._get_topology().select_server(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 233, in select_server
2024-07-12 10:54:38     return random.choice(self.select_servers(selector,
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 192, in select_servers
2024-07-12 10:54:38     server_descriptions = self._select_servers_loop(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
2024-07-12 10:54:38     raise ServerSelectionTimeoutError(
2024-07-12 10:54:38 pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [7] [INFO] Worker exiting (pid: 7)
2024-07-12 10:54:38 config
2024-07-12 10:54:38 Helpers
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [8] [ERROR] Exception in worker process
2024-07-12 10:54:38 Traceback (most recent call last):
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2024-07-12 10:54:38     worker.init_process()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
2024-07-12 10:54:38     self.load_wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2024-07-12 10:54:38     self.wsgi = self.app.wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-07-12 10:54:38     self.callable = self.load()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2024-07-12 10:54:38     return self.load_wsgiapp()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2024-07-12 10:54:38     return util.import_app(self.app_uri)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
2024-07-12 10:54:38     mod = importlib.import_module(module)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-07-12 10:54:38     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap_external>", line 1181, in exec_module
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-07-12 10:54:38   File "routes.pyx", line 8, in init routes
2024-07-12 10:54:38   File "Helpers.pyx", line 3859, in init Helpers
2024-07-12 10:54:38   File "Helpers.pyx", line 3234, in Helpers.DBHelper.__init__
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/database.py", line 1468, in authenticate
2024-07-12 10:54:38     self.client._cache_credentials(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 749, in _cache_credentials
2024-07-12 10:54:38     server = self._get_topology().select_server(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 233, in select_server
2024-07-12 10:54:38     return random.choice(self.select_servers(selector,
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 192, in select_servers
2024-07-12 10:54:38     server_descriptions = self._select_servers_loop(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
2024-07-12 10:54:38     raise ServerSelectionTimeoutError(
2024-07-12 10:54:38 pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [8] [INFO] Worker exiting (pid: 8)
2024-07-12 10:54:38 config
2024-07-12 10:54:38 Helpers
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [9] [ERROR] Exception in worker process
2024-07-12 10:54:38 Traceback (most recent call last):
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2024-07-12 10:54:38     worker.init_process()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
2024-07-12 10:54:38     self.load_wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2024-07-12 10:54:38     self.wsgi = self.app.wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-07-12 10:54:38     self.callable = self.load()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2024-07-12 10:54:38     return self.load_wsgiapp()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2024-07-12 10:54:38     return util.import_app(self.app_uri)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
2024-07-12 10:54:38     mod = importlib.import_module(module)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-07-12 10:54:38     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap_external>", line 1181, in exec_module
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-07-12 10:54:38   File "routes.pyx", line 8, in init routes
2024-07-12 10:54:38   File "Helpers.pyx", line 3859, in init Helpers
2024-07-12 10:54:38   File "Helpers.pyx", line 3234, in Helpers.DBHelper.__init__
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/database.py", line 1468, in authenticate
2024-07-12 10:54:38     self.client._cache_credentials(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 749, in _cache_credentials
2024-07-12 10:54:38     server = self._get_topology().select_server(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 233, in select_server
2024-07-12 10:54:38     return random.choice(self.select_servers(selector,
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 192, in select_servers
2024-07-12 10:54:38     server_descriptions = self._select_servers_loop(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
2024-07-12 10:54:38     raise ServerSelectionTimeoutError(
2024-07-12 10:54:38 pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [9] [INFO] Worker exiting (pid: 9)
2024-07-12 10:54:38 config
2024-07-12 10:54:38 Helpers
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [10] [ERROR] Exception in worker process
2024-07-12 10:54:38 Traceback (most recent call last):
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2024-07-12 10:54:38     worker.init_process()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
2024-07-12 10:54:38     self.load_wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2024-07-12 10:54:38     self.wsgi = self.app.wsgi()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-07-12 10:54:38     self.callable = self.load()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2024-07-12 10:54:38     return self.load_wsgiapp()
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2024-07-12 10:54:38     return util.import_app(self.app_uri)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
2024-07-12 10:54:38     mod = importlib.import_module(module)
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-07-12 10:54:38     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2024-07-12 10:54:38   File "<frozen importlib._bootstrap_external>", line 1181, in exec_module
2024-07-12 10:54:38   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-07-12 10:54:38   File "routes.pyx", line 8, in init routes
2024-07-12 10:54:38   File "Helpers.pyx", line 3859, in init Helpers
2024-07-12 10:54:38   File "Helpers.pyx", line 3234, in Helpers.DBHelper.__init__
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/database.py", line 1468, in authenticate
2024-07-12 10:54:38     self.client._cache_credentials(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 749, in _cache_credentials
2024-07-12 10:54:38     server = self._get_topology().select_server(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 233, in select_server
2024-07-12 10:54:38     return random.choice(self.select_servers(selector,
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 192, in select_servers
2024-07-12 10:54:38     server_descriptions = self._select_servers_loop(
2024-07-12 10:54:38   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
2024-07-12 10:54:38     raise ServerSelectionTimeoutError(
2024-07-12 10:54:38 pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
2024-07-12 10:54:38 [2024-07-11 22:54:38 +0000] [10] [INFO] Worker exiting (pid: 10)
2024-07-12 10:54:38 config
2024-07-12 10:54:38 Helpers
2024-07-12 10:54:39 Traceback (most recent call last):
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
2024-07-12 10:54:39     self.sleep()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
2024-07-12 10:54:39     ready = select.select([self.PIPE[0]], [], [], 1.0)
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-07-12 10:54:39     self.reap_workers()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2024-07-12 10:54:39     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-07-12 10:54:39 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-07-12 10:54:39 
2024-07-12 10:54:39 During handling of the above exception, another exception occurred:
2024-07-12 10:54:39 
2024-07-12 10:54:39 Traceback (most recent call last):
2024-07-12 10:54:39   File "/usr/local/bin/gunicorn", line 8, in <module>
2024-07-12 10:54:39     sys.exit(run())
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
2024-07-12 10:54:39     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 228, in run
2024-07-12 10:54:39     super().run()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2024-07-12 10:54:39     Arbiter(self).run()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
2024-07-12 10:54:39     self.halt(reason=inst.reason, exit_status=inst.exit_status)
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
2024-07-12 10:54:39     self.stop()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
2024-07-12 10:54:39     time.sleep(0.1)
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-07-12 10:54:39     self.reap_workers()
2024-07-12 10:54:39   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2024-07-12 10:54:39     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-07-12 10:54:39 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by Vadims06** [comment]
The issue states that it is not able to connect to mongoDB, could you please send docker ps command output, to make sure that mongo DB works properly

**Comment by nzjc** [comment]
@Vadims06 no mongodb spawns, all I see in docker ps before it dies is 
```CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS          PORTS      NAMES
4ffc731621d5   vadims06/topolograph:latest   "gunicorn -w 4 --bin…"   18 seconds ago   Up 17 seconds   5000/tcp   naughty_maxwell```

However, I ran your container on a linux host and it all worked fine - so perhaps it's just something screwy with Windows?

**Comment by Vadims06** [comment]
Indeed, the same issue `pymongo Connection refused`. Does docker-compose pull work as well?

**Comment by padawan603** [comment]
docker compose pull works for me.

ERM

**Comment by Vadims06** [comment]
I'm not sure if it still applicable. I recorded video with quick setup of Topolograph suite https://youtu.be/imtVbqQYVWQ. Please check it out and try to use `install.sh` script to recreate the environment
